Repository SrijanShovit/CrySense, pull requests merged in 2023-12, with the labels that each got.

#16 Data imbalance
  models/Readme.md
  models/class-imbalance.ipynb
Labels: CodePeak’23, medium

#13 added data distribution graph
  EDA/crysense-eda.ipynb
Labels: CodePeak’23, medium

#17 Dataframe, augmentations
  .ipynb_checkpoints/Dataframe-checkpoint.ipynb
  .ipynb_checkpoints/augmentations-checkpoint.ipynb
  Audio_Dataframe.csv
  Dataframe.ipynb
  README.md
  augmentations.ipynb
Labels: CodePeak’23, medium, EASY

#18 Feature enhancement
  Feature-extraction/crysense-feature-extraction.py
  Feature-extraction/crysense-feature-extractor.ipynb
Labels: hard, CodePeak’23
